= README

== Goals

Little Ansible role to install Redis from official repos, with a custom (and simple) configuration.

== Vars

One variable is used in the file `main.yml`. 

- `redis_auth_pass` : needed to secure (a little) the connexion
- `redis_maxclients` : default to 8600
- `redis_maxmemory` : "134217728" maxmemory in bytes, required by redis
- `redis_maxmemory_policy` : "allkeys-lru" default

== How to use it ?

=== Test it with molecule

Simple ! Use the venv.sh script to enter to the matrix (c).

[source, bash]
----
source venv.sh
----

This virtualenv will bring you needed tools. You will in the virtualenv automatically. You are now ready to create virtual machines and use the playbook.

[source, bash]
----
molecule create && molecule converge
----

When you're all set, destroy it.

[source, bash]
----
molecule destroy
----

To test it all, just do :

[source, bash]
----
molecule test
----

=== Use this role in another ansible playbook

Incorpore this role on your playbook, in the file `requirements.yml` and go !

[source, bash]
----
roles:
  - src: git@github.com:Mettmett/ansible-redis.git
    scm: git
----
