---

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: (check) Test if services are started and enabled
    command: "systemctl status redis-server.service"
    changed_when: false

  - name: (check) Test if services ports are open and reachable
    shell: "ss -ntlp | grep 6379"
    changed_when: false
