---

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: (check) Test if services are started and enabled
    systemd:
      enabled: true
      masked: false
      name: "redis"
      state: started

  - name: (check) Test if redis port is open and reachable
    wait_for:
      port: 6379
      delay: 2
